# Nome do workflow
name: Build e Testes com Python

# Gatilhos: Quando este workflow deve rodar
on:
  push:
    branches: [ "main" ] # Ao fazer push na branch main
  pull_request:
    branches: [ "main" ] # Ao abrir um pull request para a main

# Tarefas que o workflow executará
jobs:
  build:
    # A "strategy" permite criar uma matriz de configurações para rodar a mesma tarefa em diferentes ambientes
    strategy:
      matrix:
        # Roda nos 3 sistemas operacionais
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Roda em pelo menos 2 versões de Python
        python-version: ['3.9', '3.12']

    # Define o sistema operacional para a execução a partir da matriz
    runs-on: ${{ matrix.os }}

    # Passos a serem executados em cada tarefa da matriz
    steps:
    # 1. Clona o repositório para a máquina virtual do Actions
    - name: Checkout do codigo
      uses: actions/checkout@v4

    # 2. Configura a versão do Python especificada na matriz
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # 3. Instala as dependências do projeto
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # 4. Executa os testes com pytest
    - name: Executar testes
      run: python -m pytest